name: Format with Ormolu
on:
  - push
  - pull_request
jobs:
  linux:
    name: ormolu
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: mrkkrp/ormolu-action@debug
        # with:
        #   pattern: |
        #     app/**/*.hs
        #     src/**/*.hs
        #     test/**/*.hs
